export enum DocKeyTab {
   Documento = 'documento',
   ConceptosJuridicos = 'conceptosjuridicos',
   FichaTecnicaTc = 'fichatecnica-tc',
   FichaTecnicaS = 'fichatecnica-s',
   FichaTecnicaS_pub = 'fichatecnica-pub',
   FichaTecnicaT = 'fichatecnica-t',
   Indices = 'indices',
   DocumentosSugeridos = 'documentossugeridos',
   CitasSugeridas = 'citassugeridas',
   TesisRelacionadas = 'tesisrelacionadas',
   Citas = 'citas',
   DocsSugeridosCoiDH = 'docssugeridoscoidh',
   DocrelHudoc = 'docrelhudoc',
   LinJurisPrudenciales = 'linjurisprudenciales',
   LinJurisPrudencialesSent = 'linjurisprudencialesSent',
   Proactuacion = 'protactuacion',
   DocumentoSugeridos = 'documentosugeridos',
   AsuntosAbordados = 'asuntosabordados',
   RedConocimiento = 'redconocimiento',
   Catesis = 'catesis',
   Cavoto = 'cavoto',
   Descriptores = 'descriptores'
}